// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRBabyShop.Infrastructure.Data;

#nullable disable

namespace TRBabyShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221130220419_AddEmailAndNameInOrder")]
    partial class AddEmailAndNameInOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "04ba4719-a5ce-478d-b36d-169ffe19e118",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4b7193c2-0fea-4c85-881f-12262f92295d",
                            Email = "teo88@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "teo88@abv.bg",
                            NormalizedUserName = "teodor88",
                            PasswordHash = "AQAAAAEAACcQAAAAEHSUSAx1un04Sec0EZt8d+Fgm6ivvhm0DX4VKwFHDMb47zfV7kUhCVuDPz164PCMug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f3a38d3-3354-44fa-b79c-f40262b2dff1",
                            TwoFactorEnabled = false,
                            UserName = "teodor88"
                        },
                        new
                        {
                            Id = "d381c77f-aabf-46bd-80e3-cf9ee84a668b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "823b29db-2eab-4d89-a559-509dfff685ac",
                            Email = "ivan89@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ivan89@abv.bg",
                            NormalizedUserName = "ivan89",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a09c183d-709d-4ce5-8c91-60c4fe291d73",
                            TwoFactorEnabled = false,
                            UserName = "ivan89"
                        },
                        new
                        {
                            Id = "cd0f2b40-9353-405c-ae22-c1097419f287",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "977f6e06-fe8e-4bd0-9eed-ee4d80573e91",
                            Email = "hristo80@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "hristo80@abv.bg",
                            NormalizedUserName = "hristo80",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "efe7cd89-c558-4976-af01-0efab0888285",
                            TwoFactorEnabled = false,
                            UserName = "hristo80"
                        },
                        new
                        {
                            Id = "c225f1de-8898-473c-8b8d-484a5034beea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be2b93ce-6728-4734-bada-ddb2aaa151ef",
                            Email = "tina93@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "tina93@abv.bg",
                            NormalizedUserName = "tina93",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b882fd44-1247-417f-95ee-e5308de3053f",
                            TwoFactorEnabled = false,
                            UserName = "tina93"
                        });
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Car seats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bath toys"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bottle sterilizer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Baby cameras"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sleep bag"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bottle feeding"
                        });
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Dip me in water and watch me change colour",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/house-of-marbles-books-baby-touch-magic-bath-book-33551194849445_1024x1024@2x.jpg?v=1664889397",
                            Name = "Baby Touch Magic Bath Book",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Filled with beautiful, quirky illustrations and clever read-aloud rhyme, grown-ups will love reading this book to their children at any age as they lovingly consider all the possibilities that lie ahead. Its enduring message of love and acceptance as children grow and change is both universal and poignant, and is one to share over and over again.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/house-of-marbles-books-the-wonderful-things-you-will-be-book-33551190360229_1024x1024@2x.jpg?v=1664889390",
                            Name = "The Wonderful Things You Will Be - Book",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Bugaboo Turtle Air by Nuna is our ultralight car seat solution for safely transporting your newborn, from their very first ride to the everyday journeys to follow. Designed in collaboration with premium brand Nuna, it offers top comfort for your baby and seamless integration with your Bugaboo stroller. This item includes the car seat (you can purchase the Bugaboo 360 Base separately).",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/bugaboo-bugaboo-turtle-air-by-nuna-car-seat-black-33556696203429_1024x1024@2x.jpg?v=1664980829",
                            Name = "Bugaboo Turtle Air by Nuna Car Seat - Black",
                            Price = 199m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "The Mica Eco has been designed to provide convenience, safety and sustainability. The seat?s 360° rotation makes it much easier to get your children in and out of the car every day, without straining your back. Made to meet the highest i-Size safety standards, the Mica Eco features G-CELL Side Impact Protection and Eco Care 100% recycled fabrics, to safeguard a better tomorrow.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/maxi-cosi-maxi-cosi-mica-eco-i-size-authentic-black-33536085917861_1024x1024@2x.jpg?v=1664532268",
                            Name = "Maxi-Cosi Mica Eco i-Size - Authentic Black",
                            Price = 259.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Crafted from 100% textured silicone, this petal shaped teether will give your little one's sore gums relief whilst they're teething. Each petal offers a different texture to explore, with a rainbow of colours and a rattle inside to add visual and sound stimulation.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/sassy-sassy-silicone-flower-rattle-teether-32104732688549_1024x1024@2x.jpg?v=1638282702",
                            Name = "Sassy Silicone Flower Rattle Teether",
                            Price = 8.49m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Stick the suction base of this spinning toy to any flat smooth surface and spin the wheel. The soft exterior bumps make spinning easy for baby, who will love watching the rainbow appear as the wheel spins. ",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/sassy-sassy-light-up-rainbow-reel-spinning-developmental-tray-toy-6-months-32104676753573_1024x1024@2x.jpg?v=1638282346",
                            Name = "Sassy Light-Up Rainbow Reel Spinning Developmental Tray Toy - 6+ Months",
                            Price = 13.79m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "This innovation from MAM Baby features six valuable functions all in one product. Forget having to invest and store a steriliser and a bottle warmer separately, simply choose MAM for all your needs.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/mam-bottle-feeding-mam-baby-6-in-1-electric-steriliser-large-bottle-starter-bundle-32845940195493_1024x1024@2x.jpg?v=1652788714",
                            Name = "MAM Baby 6-in-1 Electric Steriliser & Large Bottle Starter Bundle - Matt Taupe",
                            Price = 165m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Steriliser, dryer and bottle storage in a purified environment",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/babymoov-babymoov-turbo-pure-steriliser-and-bottle-dryer-blue-33002899701925_1024x1024@2x.jpg?v=1656496367",
                            Name = "Babymoov Turbo Pure Steriliser and Bottle Dryer - Blue",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Thanks to Digital Green Technology, the Premium Care baby monitor combines the performance of digital technology (zero interference and clear digital sound) with low-wave emission levels to ensure baby is safe at all times. The stylish LCD touchscreen is easy to use, and the added bonus of the nightlight assist with settling baby too.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/babymoov-baby-monitors-babymoov-premium-care-audio-monitor-black-white-32248768888997_1024x1024@2x.jpg?v=1640097653",
                            Name = "Babymoov Premium Care Audio Monitor - Black & White",
                            Price = 81.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "The Angelcare® AC527 Baby Movement Monitor, with Video is a dependable, trusted and beautifully designed baby care essential. It has Angelcare®'s new 40% smaller Wireless SensAsure Movement Sensor Pad. Rest assured, the pad offers the exact same precise levels of movement detection.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/angelcare-baby-monitors-angelcare-ac527-baby-movement-monitor-with-video-sound-31667682934949_1024x1024@2x.jpg?v=1634220465",
                            Name = "Angelcare AC527 Baby Movement Monitor with Video & Sound",
                            Price = 121.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Introduce your little one to their nursery in soft, reassuring style. Mamas & Papas' Welcome to the World interiors collection is our much-loved, bestselling range. This new-look collection embraces soft pastel shades and cute woodland characters for pieces that are soft to touch and gentle against baby's sensitive skin.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/mamas-papas-dreampod-sleep-bags-swaddling-welcome-to-the-world-farm-yard-dreampod-blue-farm-print-29480443084965_1024x1024@2x.jpg?v=1628835782",
                            Name = "Welcome to the World Farm Yard Dreampod - Blue Farm Print",
                            Price = 25m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Keep your little one wrapped up warm this winter with our two pack of Dream Pod Sleep bags. Perfect for those colder nights, the zip and button-fastening design is safer than loose bedding, while the 2.5 Tog padding is sure to keep them toasty. Made with 100% jersey cotton, they're super soft and cosy, while also being gentle against baby's sensitive skin.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/mamas-papas-dreampod-sleep-bags-swaddling-dreampod-sleep-bag-0-6-months-2-5-tog-pack-of-2-balloon-18930240389285_1024x1024@2x.jpg?v=1619068305",
                            Name = "Dreampod Sleep Bag 0-6 Months 2.5 Tog (Pack of 2) - Balloon",
                            Price = 45m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "Our Complete Feeding Set contains everything you need to make baby feeding straightforward. Closer to Nature bottles have the most breast-like teat ever made. It flexes and feels like mum, so switching between breast and bottle feeding is a stress-free experience. Our Advanced Steam Steriliser can sterilise up to 6 bottles in just 5 minutes, killing 99.9% of germs that may linger in bottles, teats, breast pumps and other baby feeding accessories.",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/tommee-tippee-bottle-feeding-tommee-tippee-complete-feeding-kit-white-29069097992357_1024x1024@2x.jpg?v=1628424110",
                            Name = "Tommee Tippee Complete Feeding Kit White",
                            Price = 28m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "The kit includes our Advanced Steam Steriliser which can sterilise up to 6 bottles in just 5 minutes flat, killing 99.9% of germs that may linger in bottles, teats, breast pumps and other baby feeding accessories. ",
                            Image = "https://cdn.shopify.com/s/files/1/0414/6023/6453/products/tommee-tippee-bottle-feeding-tommee-tippee-anti-colic-complete-feeding-kit-white-29071235186853_1024x1024@2x.jpg?v=1628434206",
                            Name = "Tommee Tippee Anti Colic Complete Feeding Kit - White",
                            Price = 78m
                        });
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7127),
                            ProductId = 1,
                            Text = "Amazing item!",
                            UserId = "04ba4719-a5ce-478d-b36d-169ffe19e118"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7172),
                            ProductId = 3,
                            Text = "Very usefull!!Thank you",
                            UserId = "04ba4719-a5ce-478d-b36d-169ffe19e118"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7175),
                            ProductId = 3,
                            Text = "It`s perfect for our baby!Thank you",
                            UserId = "c225f1de-8898-473c-8b8d-484a5034beea"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7178),
                            ProductId = 8,
                            Text = "Low quality ,im very upset :(",
                            UserId = "04ba4719-a5ce-478d-b36d-169ffe19e118"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7181),
                            ProductId = 11,
                            Text = "Excellent :)",
                            UserId = "04ba4719-a5ce-478d-b36d-169ffe19e118"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7184),
                            ProductId = 11,
                            Text = "Excellent ,Thank you:)",
                            UserId = "cd0f2b40-9353-405c-ae22-c1097419f287"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7187),
                            ProductId = 12,
                            Text = "It`s really expensive for its quality ",
                            UserId = "cd0f2b40-9353-405c-ae22-c1097419f287"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7190),
                            ProductId = 4,
                            Text = "Low quality ,not impressed :(",
                            UserId = "cd0f2b40-9353-405c-ae22-c1097419f287"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7192),
                            ProductId = 7,
                            Text = "Low quality ,not impressed :(",
                            UserId = "cd0f2b40-9353-405c-ae22-c1097419f287"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7196),
                            ProductId = 9,
                            Text = "Low quality ,not impressed :(",
                            UserId = "04fa2e1b-1e98-42fa-b709-f364b63cfa91"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7199),
                            ProductId = 3,
                            Text = "Low quality ,not impressed :(",
                            UserId = "04fa2e1b-1e98-42fa-b709-f364b63cfa91"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7201),
                            ProductId = 4,
                            Text = "Very good ,thanks",
                            UserId = "727a36c2-e76e-4764-a9f6-9402f63c7872"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7204),
                            ProductId = 5,
                            Text = "Very good ,thanks",
                            UserId = "727a36c2-e76e-4764-a9f6-9402f63c7872"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7206),
                            ProductId = 8,
                            Text = "Very good ,thanks",
                            UserId = "727a36c2-e76e-4764-a9f6-9402f63c7872"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7209),
                            ProductId = 9,
                            Text = "Not recommend :(",
                            UserId = "727a36c2-e76e-4764-a9f6-9402f63c7872"
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2022, 12, 1, 0, 4, 19, 145, DateTimeKind.Local).AddTicks(7211),
                            ProductId = 10,
                            Text = "Not recommend :(",
                            UserId = "727a36c2-e76e-4764-a9f6-9402f63c7872"
                        });
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.UserProduct", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", "User")
                        .WithMany("UserReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.UserProduct", b =>
                {
                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRBabyShop.Infrastructure.Data.Models.AppUser", "User")
                        .WithMany("UserProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Navigation("UserProducts");

                    b.Navigation("UserReviews");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TRBabyShop.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
